"""Convert state_system_codes.yaml from USDOS-name-keyed to system-code-keyed format.

One-time migration script. Reads the old format (USDOS name -> {cow: ..., gw: ...})
and writes the new format (cow: {code: name}, gw: {code: name}, unmapped: [...]).
"""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OLD_YAML = ROOT / "input" / "state_system_codes.yaml"
NEW_YAML = ROOT / "input" / "state_system_codes_new.yaml"


def convert():
    with open(OLD_YAML) as f:
        old = yaml.safe_load(f)

    cow: dict[str, object] = {}
    gw: dict[str, object] = {}
    unmapped: list[str] = []
    warnings: list[str] = []

    for usdos_name, entry in old.items():
        if entry is None:
            unmapped.append(usdos_name)
            continue

        for system_key, system_dict in [("cow", cow), ("gw", gw)]:
            codes_raw = entry.get(system_key)
            if codes_raw is None:
                continue

            if isinstance(codes_raw, str):
                # Simple: cow: AFG
                _add_simple(system_dict, codes_raw, usdos_name, system_key, warnings)

            elif isinstance(codes_raw, list):
                if all(isinstance(x, str) for x in codes_raw):
                    # Multi-code: cow: [GFR, GMY]
                    for code in codes_raw:
                        _add_simple(system_dict, code, usdos_name, system_key, warnings)
                else:
                    # Date-disambiguated: cow: [{code: YUG, before: ...}, ...]
                    for rule in codes_raw:
                        code = rule["code"]
                        has_before = "before" in rule
                        has_after = "after" in rule
                        if not has_before and not has_after:
                            # No date constraints -- treat as simple
                            _add_simple(system_dict, code, usdos_name, system_key, warnings)
                        else:
                            name_rule = {"name": usdos_name}
                            if has_before:
                                name_rule["before"] = rule["before"]
                            if has_after:
                                name_rule["after"] = rule["after"]
                            _add_dated(system_dict, code, name_rule, system_key, warnings)

    if warnings:
        print("Warnings during conversion:")
        for w in warnings:
            print(f"  {w}")
        print()

    # Write new YAML
    output = {}
    output["cow"] = _sort_codes(cow)
    output["gw"] = _sort_codes(gw)
    output["unmapped"] = sorted(unmapped)

    with open(NEW_YAML, "w") as f:
        f.write("# State system code -> USDOS name mapping\n")
        f.write("# Generated by scripts/convert_mapping_format.py\n")
        f.write("#\n")
        f.write("# Format:\n")
        f.write("#   Simple: CODE: CountryName\n")
        f.write("#   Date-bounded: CODE:\n")
        f.write("#     - name: CountryA\n")
        f.write("#       before: DATE\n")
        f.write("#     - name: CountryB\n")
        f.write("#       after: DATE\n")
        f.write("#   Unmapped: USDOS names not in either state system\n")
        f.write("\n")
        yaml.dump(output, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"Wrote {NEW_YAML}")
    print(f"  COW codes: {len(cow)}")
    print(f"  GW codes: {len(gw)}")
    print(f"  Unmapped: {len(unmapped)}")


def _add_simple(system_dict: dict, code: str, name: str, system: str, warnings: list[str]):
    """Add a simple (undated) code -> name mapping."""
    if code in system_dict:
        existing = system_dict[code]
        if isinstance(existing, str):
            if existing == name:
                warnings.append(f"{system} {code}: duplicate simple entry for '{name}'")
                return
            # Two different names map to the same code without dates -- problem
            warnings.append(
                f"{system} {code}: collision between '{existing}' and '{name}' "
                f"(both undated)"
            )
            return
        else:
            # Already a list of dated entries, add this as undated -- probably wrong
            warnings.append(
                f"{system} {code}: mixing undated '{name}' with dated entries"
            )
            return
    system_dict[code] = name


def _add_dated(system_dict: dict, code: str, name_rule: dict, system: str, warnings: list[str]):
    """Add a date-bounded code -> name mapping."""
    if code in system_dict:
        existing = system_dict[code]
        if isinstance(existing, str):
            # Existing simple entry -- convert to list
            warnings.append(
                f"{system} {code}: mixing undated '{existing}' with dated entry "
                f"for '{name_rule['name']}'"
            )
            return
        else:
            # Already a list -- append
            existing.append(name_rule)
    else:
        system_dict[code] = [name_rule]


def _sort_codes(d: dict) -> dict:
    """Sort codes alphabetically."""
    return dict(sorted(d.items()))


if __name__ == "__main__":
    convert()
